// Permanent compile test for the HTML -> F# Oxpecker.Solid converter.
//
// 1. Runs src/lib/html-to-oxpecker.ts over every fixture in ./fixtures
//    (the converter is browser-only, so a linkedom DOM is installed as globals).
// 2. Emits each result as a [<SolidComponent>] into Generated.fs.
// 3. Compiles Generated.fs against the real Oxpecker.Solid NuGet package with
//    Fable. A clean Fable run means the generated DSL type-checks.
//
// Run with: pnpm test:fsharp  (requires the .NET SDK on PATH)

import { build } from "esbuild";
import { parseHTML } from "linkedom";
import { spawnSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const converterPath = join(repoRoot, "src", "lib", "html-to-oxpecker.ts");
const fixturesDir = join(here, "fixtures");
const generatedPath = join(here, "Generated.fs");
const projectPath = join(here, "OxpeckerCompileTest.fsproj");
const bundlePath = join(here, ".converter.mjs");

const log = (msg) => console.log(`\x1b[36m[fsharp-test]\x1b[0m ${msg}`);
const fail = (msg) => {
  console.error(`\x1b[31m[fsharp-test] ${msg}\x1b[0m`);
  process.exit(1);
};

/** Turns a fixture filename into a valid PascalCase F# identifier. */
function toComponentName(file) {
  const parts = basename(file, ".html").split(/[^a-zA-Z0-9]+/).filter(Boolean);
  const name = parts.map((p) => p[0].toUpperCase() + p.slice(1)).join("");
  return /^[A-Za-z]/.test(name) ? name : `View${name}`;
}

// 1. Install a DOM for the browser-only converter, then bundle + import it.
const { window, document } = parseHTML("<!doctype html><html><body></body></html>");
globalThis.window = window;
globalThis.document = document;

log("bundling converter…");
const bundled = await build({
  entryPoints: [converterPath],
  bundle: true,
  format: "esm",
  write: false,
  platform: "node",
});
writeFileSync(bundlePath, bundled.outputFiles[0].text);
const { default: HTMLtoOxpecker } = await import(
  `${pathToFileURL(bundlePath).href}?t=${Date.now()}`
);

// 2. Convert every fixture into a SolidComponent.
const fixtures = readdirSync(fixturesDir).filter((f) => f.endsWith(".html")).sort();
if (fixtures.length === 0) fail("no .html fixtures found");

let out =
  "module Generated\n\n" +
  "// AUTO-GENERATED by test/fsharp/run.mjs from test/fsharp/fixtures/*.html — do not edit.\n\n" +
  "open Oxpecker.Solid\n" +
  "open Oxpecker.Solid.Svg\n\n";

for (const file of fixtures) {
  const html = readFileSync(join(fixturesDir, file), "utf8");
  const name = toComponentName(file);
  const converter = new HTMLtoOxpecker({
    indent: "    ",
    wrapperNode: "fragment",
    component: "function",
    componentName: name,
  });
  out += `// ===== ${file} =====\n${converter.convert(html).trimEnd()}\n\n`;
  log(`converted ${file} -> ${name}`);
}
writeFileSync(generatedPath, out);
rmSync(bundlePath, { force: true });

// 3. Compile with Fable.
const isWin = process.platform === "win32";
const dotnet = (args) =>
  spawnSync("dotnet", args, { cwd: here, stdio: "inherit", shell: isWin });

log("restoring Fable tool…");
const restore = dotnet(["tool", "restore"]);
if (restore.error) fail(`could not run dotnet — is the .NET SDK installed? (${restore.error.message})`);
if (restore.status !== 0) fail("dotnet tool restore failed");

log("compiling generated F# with Fable…");
rmSync(join(here, "out"), { recursive: true, force: true });
mkdirSync(join(here, "out"), { recursive: true });
const fable = dotnet(["fable", projectPath, "--outDir", "out", "--noCache"]);
if (fable.status !== 0) fail("Fable compilation failed — generated Oxpecker DSL did not type-check");

log("\x1b[32mPASS\x1b[0m — generated F# compiles against Oxpecker.Solid");
